- name: Build iOS app
  run: |
    eas login --non-interactive -t ${{ secrets.EXPO_TOKEN }}
    eas build -p ios --non-interactive
    eas logout


on:
  push:
    branches:
      - master # Use 'master' instead of 'main' if that's the branch you're using

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm ci
        npm install -g eas-cli

    - name: Build iOS app
      run: |
        eas login -u ${{ secrets.EXPO_CLI_USERNAME }} -p ${{ secrets.EXPO_CLI_PASSWORD }}
        eas build -p ios --non-interactive
        eas logout

    - name: Download app
      run: |
        curl -Lo app.ipa "$(eas build:url --platform ios)"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: |
          ./app.ipa
